### ISSUE TITLE
License

### ISSUE THREAD

**Issue by LupusOssorum** [Overv/OOGL#24]
Would you consider relicensing (or adding an alternative license) this with the "Boost Software License" (https://opensource.org/licenses/BSL-1.0)

I am trying to make a library like this for D ([dlang.org](url)) and I would like to base my code on your OOGL library rather than starting over myself.  But, I am needing to use the BSL license.  The BSL license is very common particularly with D libraries.

Thanks for Considering,
Jonathan

**Comment by Overv** [comment]
@Fox32, @razzie, @larsmans and @Jookia, you have all contributed code to this project. Do you agree to relicense it under the Boost Software License?

**Comment by Jookia** [comment]
Please consider all my contributions to be uncopyrighted or in the public domain, meaning they can be used under any license.

**Comment by razzie** [comment]
I'll join Jookie on this. My changes are extremely minor, use them as you
see fit.

2018-02-18 1:59 GMT+01:00 Jookia <notifications@github.com>:

**Comment by Fox32** [comment]
I'm fine with the Boost Software License.

**Comment by Overv** [comment]
The license has been updated.
