### ISSUE TITLE
x64 compilation for windows platforms

### ISSUE THREAD

**Issue by gcubar** [Overv/OOGL#30]
Simple as that, how can I build and use this library into a 64 bits application?

When i do that, i receive some errors related with GWL_USERDATA preprocessor in Window_Win32.cpp file that it is not defined.

Any suggestion?
Thanks.

**Comment by Overv** [comment]
Looks like the call to `SetWindowLong` needs to be replaced: https://stackoverflow.com/questions/23083/whats-an-alternative-to-gwl-userdata-for-storing-an-object-pointer
